language: r
cache: packages
sudo:
  required

os:
 - linux
 - osx

warnings_are_errors: false

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://download.sr-support.com/software/sr-research-public-key -O ~/sr.key
 - sudo apt-key add ~/sr.key
 - sudo sh -c 'echo "deb http://download.sr-support.com/software SRResearch main" >> /etc/apt/sources.list'
 - sudo apt-get update
 - sudo apt-get install edfapi-3.1; fi

 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L -o eyelink.mpkg https://www.dropbox.com/sh/ajdg7aabu8awavv/AACn0UlNwY1MPjisdgn5JE36a?dl=1
 - sudo installer eyelink.mpkg -target /; fi

