// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// fast_sql
int fast_sql(std::string dbname, std::string sql);
RcppExport SEXP itrackR_fast_sql(SEXP dbnameSEXP, SEXP sqlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type dbname(dbnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type sql(sqlSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_sql(dbname, sql));
    return rcpp_result_gen;
END_RCPP
}
// update_rows
int update_rows(std::string dbname, NumericVector tstart, NumericVector tend);
RcppExport SEXP itrackR_update_rows(SEXP dbnameSEXP, SEXP tstartSEXP, SEXP tendSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type dbname(dbnameSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tstart(tstartSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tend(tendSEXP);
    rcpp_result_gen = Rcpp::wrap(update_rows(dbname, tstart, tend));
    return rcpp_result_gen;
END_RCPP
}
