# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_sql <- function(dbname, sql) {
    .Call('itrackR_fast_sql', PACKAGE = 'itrackR', dbname, sql)
}

update_rows <- function(dbname, tstart, tend) {
    .Call('itrackR_update_rows', PACKAGE = 'itrackR', dbname, tstart, tend)
}

